---
language: python

cache: pip

matrix:
  include:
    - os: linux
      dist: trusty
      python: "2.7"
      sudo: required
    - os: linux
      dist: xenial
      python: "2.7"
      sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # uninstall docker
  - dpkg -l|grep docker
  - sudo apt-get purge docker-ce
  - sudo rm /etc/apt/sources.list.d/docker.list
  - sudo apt-get update

script:

  # check docker is not installed
  - >
    docker ps
    && (echo 'docker installed' && exit 1)
    || (echo 'docker not installed' && exit 0)

  # run role
  - ansible-playbook tests/docker_17.09.0.yml -i tests/inventory

  # check docker is installed
  - >
    docker --version | grep 17.09.0
    && (echo 'docker installed' && exit 0)
    || (echo 'docker not installed' && exit 1)

  # test role idempotence
  - idempotence=$(mktemp)
  - ansible-playbook tests/docker_17.09.0.yml -i tests/inventory | tee -a ${idempotence}
  - >
    tail ${idempotence} | grep -q 'changed=0.*failed=0'
    && (echo 'idempotent' && exit 0)
    || (echo 'not idempotent' && exit 1)

  # upgrade docker
  - ansible-playbook tests/docker_18.03.1.yml -i tests/inventory
  # check docker downgrade
  - >
    docker --version | grep 18.03.1
    && (echo 'docker upgraded' && exit 0)
    || (echo 'docker not upgraded' && exit 1)

  # downgrade docker
  - ansible-playbook tests/docker_17.06.1.yml -i tests/inventory
  # check docker downgrade
  - >
    docker --version | grep 17.06.1
    && (echo 'docker downgraded' && exit 0)
    || (echo 'docker not downgraded' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
