---
language: python

cache: pip

matrix:
  include:
    - os: linux
      dist: xenial
      python: "3.8"
      sudo: required
    - os: linux
      dist: bionic
      python: "3.8"
      sudo: required
    - os: linux
      dist: focal
      python: "3.8"
      sudo: required

# Install ansible
addons:
  apt:
    packages:
      - python3-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # uninstall docker
  - dpkg -l|grep docker
  - sudo apt-get update
  - sudo apt-get purge docker-ce

script:

  # check docker is not installed
  - >
    docker ps
    && (echo 'docker installed' && exit 1)
    || (echo 'docker not installed' && exit 0)

  # run role
  - ansible-playbook tests/docker_20.10.2.yml -i tests/inventory

  # check docker is installed
  - docker --version
  - >
    docker --version | grep 20.10.2
    && (echo 'docker installed' && exit 0)
    || (echo 'docker not installed' && exit 1)

  # test role idempotence
  - idempotence=$(mktemp)
  - ansible-playbook tests/docker_20.10.2.yml -i tests/inventory | tee -a ${idempotence}
  - >
    tail ${idempotence} | grep -q 'changed=0.*failed=0'
    && (echo 'idempotent' && exit 0)
    || (echo 'not idempotent' && exit 1)

  # upgrade docker
  - ansible-playbook tests/docker_20.10.3.yml -i tests/inventory
  # check docker downgrade
  - docker --version
  - >
    docker --version | grep 20.10.3
    && (echo 'docker upgraded' && exit 0)
    || (echo 'docker not upgraded' && exit 1)

  # downgrade docker
  - ansible-playbook tests/docker_20.10.1.yml -i tests/inventory
  # check docker downgrade
  - docker --version
  - >
    docker --version | grep 20.10.1
    && (echo 'docker downgraded' && exit 0)
    || (echo 'docker not downgraded' && exit 1)

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_cancel: never
    on_failure: never
    on_error: never
